// Config bindings — thin wrappers over the auto-generated Wails bridge.
// Kept separate because the wailsjs/ files are regenerated by `wails dev`
// and may be root-owned in the Docker dev environment.

export interface ServerEntry {
  name: string
  addr: string
}

export interface Config {
  theme: string
  username: string
  input_device_id: number
  output_device_id: number
  volume: number
  noise_enabled: boolean
  noise_level: number
  aec_enabled: boolean
  agc_enabled: boolean
  agc_level: number
  vad_enabled: boolean
  vad_threshold: number
  ptt_enabled: boolean
  ptt_key: string
  servers: ServerEntry[]
}

/* eslint-disable @typescript-eslint/no-explicit-any */
const bridge = () => (window as any)['go']['main']['App']

export function ApplyConfig(): Promise<void> {
  return bridge()['ApplyConfig']()
}

export function GetConfig(): Promise<Config> {
  return bridge()['GetConfig']()
}

export function SaveConfig(cfg: Config): Promise<void> {
  return bridge()['SaveConfig'](cfg)
}

// --- AEC bindings ---

export function SetAEC(enabled: boolean): Promise<void> {
  return bridge()['SetAEC'](enabled)
}

// --- AGC bindings ---

export function SetAGC(enabled: boolean): Promise<void> {
  return bridge()['SetAGC'](enabled)
}

export function SetAGCLevel(level: number): Promise<void> {
  return bridge()['SetAGCLevel'](level)
}

// --- VAD bindings ---

export function SetVAD(enabled: boolean): Promise<void> {
  return bridge()['SetVAD'](enabled)
}

export function SetVADThreshold(level: number): Promise<void> {
  return bridge()['SetVADThreshold'](level)
}

// --- PTT bindings ---

export function SetPTTMode(enabled: boolean): Promise<void> {
  return bridge()['SetPTTMode'](enabled)
}

export function PTTKeyDown(): Promise<void> {
  return bridge()['PTTKeyDown']()
}

export function PTTKeyUp(): Promise<void> {
  return bridge()['PTTKeyUp']()
}

// --- Per-user local mute bindings ---

export function MuteUser(id: number): Promise<void> {
  return bridge()['MuteUser'](id)
}

export function UnmuteUser(id: number): Promise<void> {
  return bridge()['UnmuteUser'](id)
}

export function GetMutedUsers(): Promise<number[]> {
  return bridge()['GetMutedUsers']()
}

// --- Chat bindings ---

export function SendChat(message: string): Promise<string> {
  return bridge()['SendChat'](message)
}

// --- Moderation bindings ---

export function KickUser(id: number): Promise<string> {
  return bridge()['KickUser'](id)
}

export function RenameServer(name: string): Promise<string> {
  return bridge()['RenameServer'](name)
}

// --- Invite link / startup ---

export function GetStartupAddr(): Promise<string> {
  return bridge()['GetStartupAddr']()
}

// --- Channel bindings ---

export function JoinChannel(id: number): Promise<string> {
  return bridge()['JoinChannel'](id)
}

export function ConnectVoice(channelID: number): Promise<string> {
  return bridge()['ConnectVoice'](channelID)
}

export function SendChannelChat(channelID: number, message: string): Promise<string> {
  return bridge()['SendChannelChat'](channelID, message)
}

// --- Channel management bindings (owner-only) ---

export function CreateChannel(name: string): Promise<string> {
  return bridge()['CreateChannel'](name)
}

export function RenameChannel(id: number, name: string): Promise<string> {
  return bridge()['RenameChannel'](id, name)
}

export function DeleteChannel(id: number): Promise<string> {
  return bridge()['DeleteChannel'](id)
}

export function MoveUserToChannel(userID: number, channelID: number): Promise<string> {
  return bridge()['MoveUserToChannel'](userID, channelID)
}

// --- File upload bindings ---

export function UploadFile(channelID: number): Promise<string> {
  return bridge()['UploadFile'](channelID)
}

export function UploadFileFromPath(channelID: number, path: string): Promise<string> {
  return bridge()['UploadFileFromPath'](channelID, path)
}
