// Config bindings — thin wrappers over the auto-generated Wails bridge.
// Kept separate because the wailsjs/ files are regenerated by `wails dev`
// and may be root-owned in the Docker dev environment.

export interface ServerEntry {
  name: string
  addr: string
}

export type MessageDensity = 'compact' | 'default' | 'comfortable'

export interface Config {
  theme: string
  theme_mode?: string
  username: string
  input_device_id: number
  output_device_id: number
  volume: number
  audio_bitrate_kbps: number
  noise_enabled: boolean
  aec_enabled: boolean
  agc_enabled: boolean
  ptt_enabled: boolean
  ptt_key: string
  servers: ServerEntry[]
  message_density?: MessageDensity
  show_system_messages?: boolean
  // Legacy fields persisted by older builds. Kept optional for compatibility.
  noise_level?: number
  agc_level?: number
}

/* eslint-disable @typescript-eslint/no-explicit-any */
const bridge = () => (window as any)['go']['main']['App']

export function ApplyConfig(): Promise<void> {
  return bridge()['ApplyConfig']()
}

export function GetConfig(): Promise<Config> {
  return bridge()['GetConfig']()
}

export function SaveConfig(cfg: Config): Promise<void> {
  return bridge()['SaveConfig'](cfg)
}

// --- AEC bindings ---

export function SetAEC(enabled: boolean): Promise<void> {
  return bridge()['SetAEC'](enabled)
}

// --- AGC bindings ---

export function SetAGC(enabled: boolean): Promise<void> {
  return bridge()['SetAGC'](enabled)
}

export function SetAGCLevel(level: number): Promise<void> {
  return bridge()['SetAGCLevel'](level)
}

// --- Audio bitrate bindings ---

export function SetAudioBitrate(kbps: number): Promise<void> {
  return bridge()['SetAudioBitrate'](kbps)
}

export function GetAudioBitrate(): Promise<number> {
  return bridge()['GetAudioBitrate']()
}

// --- Input Level bindings ---

export function GetInputLevel(): Promise<number> {
  return bridge()['GetInputLevel']()
}

// --- Notification Volume bindings ---

export function SetNotificationVolume(volume: number): Promise<void> {
  return bridge()['SetNotificationVolume'](volume)
}

export function GetNotificationVolume(): Promise<number> {
  return bridge()['GetNotificationVolume']()
}

// --- PTT bindings ---

export function SetPTTMode(enabled: boolean): Promise<void> {
  return bridge()['SetPTTMode'](enabled)
}

export function PTTKeyDown(): Promise<void> {
  return bridge()['PTTKeyDown']()
}

export function PTTKeyUp(): Promise<void> {
  return bridge()['PTTKeyUp']()
}

// --- Per-user local mute bindings ---

export function MuteUser(id: number): Promise<void> {
  return bridge()['MuteUser'](id)
}

export function UnmuteUser(id: number): Promise<void> {
  return bridge()['UnmuteUser'](id)
}

export function GetMutedUsers(): Promise<number[]> {
  return bridge()['GetMutedUsers']()
}

// --- Per-user volume bindings ---

export function SetUserVolume(userID: number, volume: number): Promise<void> {
  return bridge()['SetUserVolume'](userID, volume)
}

export function GetUserVolume(userID: number): Promise<number> {
  return bridge()['GetUserVolume'](userID)
}

// --- Chat bindings ---

export function SendChat(message: string): Promise<string> {
  return bridge()['SendChat'](message)
}

export function EditMessage(msgID: number, message: string): Promise<string> {
  return bridge()['EditMessage'](msgID, message)
}

export function DeleteMessage(msgID: number): Promise<string> {
  return bridge()['DeleteMessage'](msgID)
}

export function AddReaction(msgID: number, emoji: string): Promise<string> {
  return bridge()['AddReaction'](msgID, emoji)
}

export function RemoveReaction(msgID: number, emoji: string): Promise<string> {
  return bridge()['RemoveReaction'](msgID, emoji)
}

export function SendTyping(channelID: number): Promise<string> {
  return bridge()['SendTyping'](channelID)
}

// --- Moderation bindings ---

export function KickUser(id: number): Promise<string> {
  return bridge()['KickUser'](id)
}

export function RenameServer(name: string): Promise<string> {
  return bridge()['RenameServer'](name)
}

export function RenameUser(name: string): Promise<string> {
  return bridge()['RenameUser'](name)
}

// --- Invite link / startup ---

export function GetStartupAddr(): Promise<string> {
  return bridge()['GetStartupAddr']()
}

export function GetBuildInfo(): Promise<{
  commit: string
  build_time: string
  go_version: string
  goos: string
  goarch: string
  dirty: boolean
}> {
  return bridge()['GetBuildInfo']()
}

// --- Channel bindings ---

export function JoinChannel(id: number): Promise<string> {
  return bridge()['JoinChannel'](id)
}

export function ConnectVoice(channelID: number): Promise<string> {
  return bridge()['ConnectVoice'](channelID)
}

export function SendChannelChat(channelID: number, message: string): Promise<string> {
  return bridge()['SendChannelChat'](channelID, message)
}

// --- Channel management bindings (owner-only) ---

export function CreateChannel(name: string): Promise<string> {
  return bridge()['CreateChannel'](name)
}

export function RenameChannel(id: number, name: string): Promise<string> {
  return bridge()['RenameChannel'](id, name)
}

export function DeleteChannel(id: number): Promise<string> {
  return bridge()['DeleteChannel'](id)
}

export function MoveUserToChannel(userID: number, channelID: number): Promise<string> {
  return bridge()['MoveUserToChannel'](userID, channelID)
}

// --- File upload bindings ---

export function UploadFile(channelID: number): Promise<string> {
  return bridge()['UploadFile'](channelID)
}

export function UploadFileFromPath(channelID: number, path: string): Promise<string> {
  return bridge()['UploadFileFromPath'](channelID, path)
}

// --- Video bindings ---

export function StartVideo(): Promise<string> {
  return bridge()['StartVideo']()
}

export function StopVideo(): Promise<string> {
  return bridge()['StopVideo']()
}

export function StartScreenShare(): Promise<string> {
  return bridge()['StartScreenShare']()
}

export function StopScreenShare(): Promise<string> {
  return bridge()['StopScreenShare']()
}

// --- Recording bindings ---

export function StartRecording(channelID: number): Promise<string> {
  return bridge()['StartRecording'](channelID)
}

export function StopRecording(channelID: number): Promise<string> {
  return bridge()['StopRecording'](channelID)
}

// --- Video quality bindings ---

export function RequestVideoQuality(targetUserID: number, quality: string): Promise<string> {
  return bridge()['RequestVideoQuality'](targetUserID, quality)
}

// --- Multi-server session bindings ---

export function SetActiveServer(addr: string): Promise<string> {
  const fn = bridge()['SetActiveServer']
  if (typeof fn !== 'function') return Promise.resolve('')
  return fn(addr)
}

export function DisconnectServer(addr: string): Promise<string> {
  const fn = bridge()['DisconnectServer']
  if (typeof fn !== 'function') return Promise.resolve('')
  return fn(addr)
}
