// Config bindings — thin wrappers over the auto-generated Wails bridge.
// Kept separate because the wailsjs/ files are regenerated by `wails dev`
// and may be root-owned in the Docker dev environment.

export interface ServerEntry {
  name: string
  addr: string
}

export interface Config {
  theme: string
  username: string
  input_device_id: number
  output_device_id: number
  volume: number
  noise_enabled: boolean
  noise_level: number
  servers: ServerEntry[]
}

/* eslint-disable @typescript-eslint/no-explicit-any */
const bridge = () => (window as any)['go']['main']['App']

export function GetConfig(): Promise<Config> {
  return bridge()['GetConfig']()
}

export function SaveConfig(cfg: Config): Promise<void> {
  return bridge()['SaveConfig'](cfg)
}
