// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function ApplyConfig():Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<string>;

export function ConnectVoice(arg1:number):Promise<string>;

export function CreateChannel(arg1:string):Promise<string>;

export function DeleteChannel(arg1:number):Promise<string>;

export function DeleteMessage(arg1:number):Promise<string>;

export function Disconnect():Promise<void>;

export function DisconnectVoice():Promise<string>;

export function EditMessage(arg1:number,arg2:string):Promise<string>;

export function GetAutoLogin():Promise<main.AutoLogin>;

export function GetConfig():Promise<config.Config>;

export function GetInputDevices():Promise<Array<main.AudioDevice>>;

export function GetMetrics():Promise<main.Metrics>;

export function GetMutedUsers():Promise<Array<number>>;

export function GetOutputDevices():Promise<Array<main.AudioDevice>>;

export function GetStartupAddr():Promise<string>;

export function IsConnected():Promise<boolean>;

export function JoinChannel(arg1:number):Promise<string>;

export function KickUser(arg1:number):Promise<string>;

export function MoveUserToChannel(arg1:number,arg2:number):Promise<string>;

export function MuteUser(arg1:number):Promise<void>;

export function PTTKeyDown():Promise<void>;

export function PTTKeyUp():Promise<void>;

export function RenameChannel(arg1:number,arg2:string):Promise<string>;

export function RenameServer(arg1:string):Promise<string>;

export function RenameUser(arg1:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SendChannelChat(arg1:number,arg2:string):Promise<string>;

export function SendChat(arg1:string):Promise<string>;

export function SetAEC(arg1:boolean):Promise<void>;

export function SetAGC(arg1:boolean):Promise<void>;

export function SetAGCLevel(arg1:number):Promise<void>;

export function SetDeafened(arg1:boolean):Promise<void>;

export function SetInputDevice(arg1:number):Promise<void>;

export function SetMuted(arg1:boolean):Promise<void>;

export function SetNoiseSuppression(arg1:boolean):Promise<void>;

export function SetNoiseSuppressionLevel(arg1:number):Promise<void>;

export function SetOutputDevice(arg1:number):Promise<void>;

export function SetPTTMode(arg1:boolean):Promise<void>;

export function SetVAD(arg1:boolean):Promise<void>;

export function SetVADThreshold(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function StartTest():Promise<string>;

export function StopTest():Promise<void>;

export function UnmuteUser(arg1:number):Promise<void>;

export function UploadFile(arg1:number):Promise<string>;

export function UploadFileFromPath(arg1:number,arg2:string):Promise<string>;
