// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReaction(arg1, arg2) {
  return window['go']['main']['App']['AddReaction'](arg1, arg2);
}

export function ApplyConfig() {
  return window['go']['main']['App']['ApplyConfig']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function ConnectVoice(arg1) {
  return window['go']['main']['App']['ConnectVoice'](arg1);
}

export function CreateChannel(arg1) {
  return window['go']['main']['App']['CreateChannel'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DisconnectVoice() {
  return window['go']['main']['App']['DisconnectVoice']();
}

export function EditMessage(arg1, arg2) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2);
}

export function GetAudioBitrate() {
  return window['go']['main']['App']['GetAudioBitrate']();
}

export function GetAutoLogin() {
  return window['go']['main']['App']['GetAutoLogin']();
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInputDevices() {
  return window['go']['main']['App']['GetInputDevices']();
}

export function GetInputLevel() {
  return window['go']['main']['App']['GetInputLevel']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetMutedUsers() {
  return window['go']['main']['App']['GetMutedUsers']();
}

export function GetNotificationVolume() {
  return window['go']['main']['App']['GetNotificationVolume']();
}

export function GetOutputDevices() {
  return window['go']['main']['App']['GetOutputDevices']();
}

export function GetStartupAddr() {
  return window['go']['main']['App']['GetStartupAddr']();
}

export function GetUserVolume(arg1) {
  return window['go']['main']['App']['GetUserVolume'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function KickUser(arg1) {
  return window['go']['main']['App']['KickUser'](arg1);
}

export function MoveUserToChannel(arg1, arg2) {
  return window['go']['main']['App']['MoveUserToChannel'](arg1, arg2);
}

export function MuteUser(arg1) {
  return window['go']['main']['App']['MuteUser'](arg1);
}

export function PTTKeyDown() {
  return window['go']['main']['App']['PTTKeyDown']();
}

export function PTTKeyUp() {
  return window['go']['main']['App']['PTTKeyUp']();
}

export function RemoveReaction(arg1, arg2) {
  return window['go']['main']['App']['RemoveReaction'](arg1, arg2);
}

export function RenameChannel(arg1, arg2) {
  return window['go']['main']['App']['RenameChannel'](arg1, arg2);
}

export function RenameServer(arg1) {
  return window['go']['main']['App']['RenameServer'](arg1);
}

export function RenameUser(arg1) {
  return window['go']['main']['App']['RenameUser'](arg1);
}

export function RequestChannels() {
  return window['go']['main']['App']['RequestChannels']();
}

export function RequestMessages(arg1) {
  return window['go']['main']['App']['RequestMessages'](arg1);
}

export function RequestServerInfo() {
  return window['go']['main']['App']['RequestServerInfo']();
}

export function RequestVideoQuality(arg1, arg2) {
  return window['go']['main']['App']['RequestVideoQuality'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendChannelChat(arg1, arg2) {
  return window['go']['main']['App']['SendChannelChat'](arg1, arg2);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetAEC(arg1) {
  return window['go']['main']['App']['SetAEC'](arg1);
}

export function SetAGC(arg1) {
  return window['go']['main']['App']['SetAGC'](arg1);
}

export function SetAudioBitrate(arg1) {
  return window['go']['main']['App']['SetAudioBitrate'](arg1);
}

export function SetDeafened(arg1) {
  return window['go']['main']['App']['SetDeafened'](arg1);
}

export function SetInputDevice(arg1) {
  return window['go']['main']['App']['SetInputDevice'](arg1);
}

export function SetMuted(arg1) {
  return window['go']['main']['App']['SetMuted'](arg1);
}

export function SetNoiseSuppression(arg1) {
  return window['go']['main']['App']['SetNoiseSuppression'](arg1);
}

export function SetNotificationVolume(arg1) {
  return window['go']['main']['App']['SetNotificationVolume'](arg1);
}

export function SetOutputDevice(arg1) {
  return window['go']['main']['App']['SetOutputDevice'](arg1);
}

export function SetPTTMode(arg1) {
  return window['go']['main']['App']['SetPTTMode'](arg1);
}

export function SetUserVolume(arg1, arg2) {
  return window['go']['main']['App']['SetUserVolume'](arg1, arg2);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StartScreenShare() {
  return window['go']['main']['App']['StartScreenShare']();
}

export function StartTest() {
  return window['go']['main']['App']['StartTest']();
}

export function StartVideo() {
  return window['go']['main']['App']['StartVideo']();
}

export function StopScreenShare() {
  return window['go']['main']['App']['StopScreenShare']();
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}

export function StopVideo() {
  return window['go']['main']['App']['StopVideo']();
}

export function UnmuteUser(arg1) {
  return window['go']['main']['App']['UnmuteUser'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}

export function UploadFileFromPath(arg1, arg2) {
  return window['go']['main']['App']['UploadFileFromPath'](arg1, arg2);
}
