// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string):Promise<string>;

export function Disconnect():Promise<void>;

export function GetAutoLogin():Promise<main.AutoLogin>;

export function GetInputDevices():Promise<Array<main.AudioDevice>>;

export function GetMetrics():Promise<main.Metrics>;

export function GetOutputDevices():Promise<Array<main.AudioDevice>>;

export function IsConnected():Promise<boolean>;

export function SetInputDevice(arg1:number):Promise<void>;

export function SetNoiseSuppression(arg1:boolean):Promise<void>;

export function SetNoiseSuppressionLevel(arg1:number):Promise<void>;

export function SetOutputDevice(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function StartTest():Promise<string>;

export function StopTest():Promise<void>;
