// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfig() {
  return window['go']['main']['App']['ApplyConfig']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function ConnectVoice(arg1) {
  return window['go']['main']['App']['ConnectVoice'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DisconnectVoice() {
  return window['go']['main']['App']['DisconnectVoice']();
}

export function GetAutoLogin() {
  return window['go']['main']['App']['GetAutoLogin']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInputDevices() {
  return window['go']['main']['App']['GetInputDevices']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetMutedUsers() {
  return window['go']['main']['App']['GetMutedUsers']();
}

export function GetOutputDevices() {
  return window['go']['main']['App']['GetOutputDevices']();
}

export function GetStartupAddr() {
  return window['go']['main']['App']['GetStartupAddr']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function KickUser(arg1) {
  return window['go']['main']['App']['KickUser'](arg1);
}

export function MuteUser(arg1) {
  return window['go']['main']['App']['MuteUser'](arg1);
}

export function RenameServer(arg1) {
  return window['go']['main']['App']['RenameServer'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendChannelChat(arg1, arg2) {
  return window['go']['main']['App']['SendChannelChat'](arg1, arg2);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetAEC(arg1) {
  return window['go']['main']['App']['SetAEC'](arg1);
}

export function SetAGC(arg1) {
  return window['go']['main']['App']['SetAGC'](arg1);
}

export function SetAGCLevel(arg1) {
  return window['go']['main']['App']['SetAGCLevel'](arg1);
}

export function SetDeafened(arg1) {
  return window['go']['main']['App']['SetDeafened'](arg1);
}

export function SetInputDevice(arg1) {
  return window['go']['main']['App']['SetInputDevice'](arg1);
}

export function SetMuted(arg1) {
  return window['go']['main']['App']['SetMuted'](arg1);
}

export function SetNoiseSuppression(arg1) {
  return window['go']['main']['App']['SetNoiseSuppression'](arg1);
}

export function SetNoiseSuppressionLevel(arg1) {
  return window['go']['main']['App']['SetNoiseSuppressionLevel'](arg1);
}

export function SetOutputDevice(arg1) {
  return window['go']['main']['App']['SetOutputDevice'](arg1);
}

export function SetVAD(arg1) {
  return window['go']['main']['App']['SetVAD'](arg1);
}

export function SetVADThreshold(arg1) {
  return window['go']['main']['App']['SetVADThreshold'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StartTest() {
  return window['go']['main']['App']['StartTest']();
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}

export function UnmuteUser(arg1) {
  return window['go']['main']['App']['UnmuteUser'](arg1);
}
