// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAutoLogin() {
  return window['go']['main']['App']['GetAutoLogin']();
}

export function GetInputDevices() {
  return window['go']['main']['App']['GetInputDevices']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetOutputDevices() {
  return window['go']['main']['App']['GetOutputDevices']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SetDeafened(arg1) {
  return window['go']['main']['App']['SetDeafened'](arg1);
}

export function SetInputDevice(arg1) {
  return window['go']['main']['App']['SetInputDevice'](arg1);
}

export function SetMuted(arg1) {
  return window['go']['main']['App']['SetMuted'](arg1);
}

export function SetNoiseSuppression(arg1) {
  return window['go']['main']['App']['SetNoiseSuppression'](arg1);
}

export function SetNoiseSuppressionLevel(arg1) {
  return window['go']['main']['App']['SetNoiseSuppressionLevel'](arg1);
}

export function SetOutputDevice(arg1) {
  return window['go']['main']['App']['SetOutputDevice'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StartTest() {
  return window['go']['main']['App']['StartTest']();
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}
